FROM openjdk:11

ARG DATABASE_DRIVER_NAME
ARG DATABASE_URL
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG OAUTH2_GOOGLE_CLIENT_ID
ARG OAUTH2_GOOGLE_SECRET
ARG OAUTH2_GOOGLE_REDIRECT_URI
ARG OAUTH2_NAVER_CLIENT
ARG OAUTH2_NAVER_SECRET
ARG OAUTH2_NAVER_REDIRECT_URI
ARG JWT_SECRETKEY
ARG JWT_ACCESSS_TOKEN_EXPRIATION_TIME
ARG JWT_REFRESH_TOKEN_EXPRIATION_TIME
ARG JWT_REDIRECT_URI


ENV DATABASE_DRIVER_NAME=${DATABASE_DRIVER_NAME}
ENV DATABASE_URL=${DATABASE_URL}
ENV DATABASE_USERNAME=#{DATABASE_USERNAME}
ENV DATABASE_PASSWORD=#{DATABASE_PASSWORD}
ENV OAUTH2_GOOGLE_CLIENT_ID=${OAUTH2_GOOGLE_CLIENT_ID}
ENV OAUTH2_GOOGLE_SECRET=${OAUTH2_GOOGLE_SECRET}
ENV OAUTH2_GOOGLE_REDIRECT_URI=${OAUTH2_GOOGLE_REDIRECT_URI}
ENV OAUTH2_NAVER_CLIENT=${OAUTH2_NAVER_CLIENT}
ENV OAUTH2_NAVER_SECRET=${OAUTH2_NAVER_SECRET}
ENV OAUTH2_NAVER_REDIRECT_URI=${OAUTH2_NAVER_REDIRECT_URI}
ENV JWT_SECRETKEY=${JWT_SECRETKEY}
ENV JWT_ACCESSS_TOKEN_EXPRIATION_TIME=${JWT_ACCESSS_TOKEN_EXPRIATION_TIME}
ENV JWT_REFRESH_TOKEN_EXPRIATION_TIME=${JWT_REFRESH_TOKEN_EXPRIATION_TIME}
ENV JWT_REDIRECT_URI=${JWT_REDIRECT_URI}

WORKDIR /app
COPY UserService-0.0.1-SNAPSHOT.jar /app/app.jar
ENTRYPOINT ["java","-jar","app.jar"]