app:
  application:
    name: UserService

# 서버포트
server:
  port: 8181

spring:
  datasource:
    hikari:
      driver-class-name: ${DATABASE_DRIVER_NAME}
      jdbc-url: ${DATABASE_URL}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
  devtools:
    restart: # 리로드, 리스타시 devtools모듈이 리로드 실행
      enabled: true
    livereload:
      enabled: true
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_SECRET}
            redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI}
          naver:
            client-id: ${OAUTH2_NAVER_CLIENT}
            client-secret: ${OAUTH2_NAVER_SECRET}
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${OAUTH2_NAVER_REDIRECT_URI}
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
jwt:
  secretKey: ${JWT_SECRETKEY}
  access-token:
    expiration-time: ${JWT_ACCESSS_TOKEN_EXPRIATION_TIME}
  refresh-token:
    expiration-time: ${JWT_REFRESH_TOKEN_EXPRIATION_TIME}
  redirect-uri: ${JWT_REDIRECT_URI}


springdoc:
  api-docs:
    path: /public/api-docs
  swagger-ui:
    path: /public/swagger-ui.html

logging:
  level:
    com.mallproject: debug






