name: CI/CD USER-SERVICE
       
on:
  push:
    branches: [ "master" ]
  
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_DRIVER_NAME: ${{secrets.DATABASE_DRIVER_NAME}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}

      OAUTH2_GOOGLE_CLIENT_ID: ${{secrets.OAUTH2_GOOGLE_CLIENT_ID}}
      OAUTH2_GOOGLE_SECRET: ${{secrets.OAUTH2_GOOGLE_SECRET}}
      OAUTH2_GOOGLE_REDIRECT_URI: ${{secrets.OAUTH2_GOOGLE_REDIRECT_URI}}

      OAUTH2_NAVER_CLIENT: ${{secrets.OAUTH2_NAVER_CLIENT}}
      OAUTH2_NAVER_SECRET: ${{secrets.OAUTH2_NAVER_SECRET}}
      OAUTH2_NAVER_REDIRECT_URI: ${{secrets.OAUTH2_NAVER_REDIRECT_URI}}

      JWT_SECRETKEY: ${{secrets.JWT_SECRETKEY}}
      JWT_ACCESSS_TOKEN_EXPRIATION_TIME: ${{secrets.JWT_ACCESSS_TOKEN_EXPRIATION_TIME}}
      JWT_REFRESH_TOKEN_EXPRIATION_TIME: ${{secrets.JWT_REFRESH_TOKEN_EXPRIATION_TIME}}
      JWT_REDIRECT_URI: ${{secrets.JWT_REDIRECT_URI}}

    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

          
      - name: Grant execute permission for Gradle and build
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test
 

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}


      - name: Build Docker Image
        run: docker build --build-arg DATABASE_DRIVER_NAME=${{env.DATABASE_DRIVER_NAME}} \
          --build-arg DATABASE_URL=${{env.DATABASE_URL}} \
          --build-arg DATABASE_USERNAME=${{env.DATABASE_USERNAME}} \
          --build-arg DATABASE_PASSWORD=${{env.DATABASE_PASSWORD}} \
          --build-arg OAUTH2_GOOGLE_CLIENT_ID=${{env.OAUTH2_GOOGLE_CLIENT_ID}} \
          --build-arg OAUTH2_GOOGLE_SECRET=${{env.OAUTH2_GOOGLE_SECRET}} \
          --build-arg OAUTH2_GOOGLE_REDIRECT_URI=${{env.OAUTH2_GOOGLE_REDIRECT_URI}} \
          --build-arg OAUTH2_NAVER_CLIENT=${{env.OAUTH2_NAVER_CLIENT}} \
          --build-arg OAUTH2_NAVER_SECRET=${{env.OAUTH2_NAVER_SECRET}} \
          --build-arg OAUTH2_NAVER_REDIRECT_URI=${{env.OAUTH2_NAVER_REDIRECT_URI}} \
          --build-arg JWT_SECRETKEY=${{env.JWT_SECRETKEY}} \
          --build-arg JWT_ACCESSS_TOKEN_EXPRIATION_TIME=${{env.JWT_ACCESSS_TOKEN_EXPRIATION_TIME}} \
          --build-arg JWT_REFRESH_TOKEN_EXPRIATION_TIME=${{env.JWT_REFRESH_TOKEN_EXPRIATION_TIME}} \
          --build-arg JWT_REDIRECT_URI=${{env.JWT_REDIRECT_URI}} \
	-t ${{secrets.DOCKERHUB_USERNAME}}/userservice:latest .


      - name: Push Image 
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/userservice:latest

